
server:
  port: 8080
  servlet:
    context-path: /auth



logging:
  level:
    org.springframework.security: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: false
